export function mockHsMapSwipeService() {
  return jasmine.createSpyObj('HsMapSwipeService', [
    'setInitCtrlActive',
    'setInitOri',
    'updateUrlParam',
    'updateStorageOri',
    'initSwipeControl',
    'layersAvailable',
    'setOrientation',
    'fillSwipeLayers',
    'addSwipeLayer',
    'moveSwipeLayer',
    'moveRight',
    'moveLeft',
    'setControl',
    'removeCompletely',
    'setLayerActive',
    'setInitialSwipeLayers',
    'checkForMissingLayers',
    'sortLayers',
    'changeLayerVisibility',
    'layerVisibilityChanged',
    'findLayer',
  ]);
}
