export const KEYWORDS: any[] = [
  {name: 'Basemap', value: 'Basemap', selected: false},
  {name: 'Borders', value: 'Borders', selected: false},
  {name: 'Physical geography', value: 'Physical geography', selected: false},
  {name: 'Demographics', value: 'Demographics', selected: false},
  {name: 'Economics', value: 'Economics', selected: false},
  {
    name: 'Socio political conditions',
    value: 'Socio political conditions',
    selected: false,
  },
  {name: 'Culture', value: 'Culture', selected: false},
  {name: 'Transport', value: 'Transport', selected: false},
  {name: 'Land use', value: 'Land use', selected: false},
  {name: 'Environment', value: 'Environment', selected: false},
  {name: 'Water', value: 'Water', selected: false},
  {name: 'Hazards', value: 'Hazards', selected: false},
  {name: 'Cadastre', value: 'Cadastre', selected: false},
  {name: 'Infrastructure', value: 'Infrastructure', selected: false},
  {name: 'Real estate', value: 'Real estate', selected: false},
  {name: 'Planning', value: 'Planning', selected: false},
  {name: 'Complex information', value: 'Complex information', selected: false},
];
export const INSPIRETHEMES: any[] = [
  {name: 'None', value: 'None'},
  {name: 'Addresses', value: 'Addresses'},
  {name: 'Administrative units', value: 'Administrative units'},
  {name: 'Coordinate reference systems', value: 'Coordinate reference systems'},
  {name: 'Geographical grid systems', value: 'Geographical grid systems'},
  {name: 'Cadastral parcels', value: 'Cadastral parcels'},
  {name: 'Geographical names', value: 'Geographical names'},
  {name: 'Hydrography', value: 'Hydrography'},
  {name: 'Protected sites', value: 'Protected sites'},
  {name: 'Transport networks', value: 'Transport networks'},
  {name: 'Elevation', value: 'Elevation'},
  {name: 'Geology', value: 'Geology'},
  {name: 'Land cover', value: 'Land cover'},
  {name: 'Orthoimagery', value: 'Orthoimagery'},
  {
    name: 'Agricultural and aquaculture facilities',
    value: 'Agricultural and aquaculture facilities',
  },
  {
    name: 'Area management/restriction/regulation zones and reporting units',
    value: 'Area management/restriction/regulation zones and reporting units',
  },
  {name: 'Atmospheric conditions', value: 'Atmospheric conditions'},
  {name: 'Bio-geographical regions', value: 'Bio-geographical regions'},
  {name: 'Buildings', value: 'Buildings'},
  {name: 'Energy resources', value: 'Energy resources'},
  {
    name: 'Environmental monitoring facilities',
    value: 'Environmental monitoring facilities',
  },
  {name: 'Habitants and biotopes', value: 'Habitants and biotopes'},
  {name: 'Human health and safety', value: 'Human health and safety'},
  {name: 'Land use', value: 'Land use'},
  {name: 'Mineral resources', value: 'Mineral resources'},
  {name: 'Natural risk zones', value: 'Natural risk zones'},
  {
    name: 'Oceanographic geographical features',
    value: 'Oceanographic geographical features',
  },
  {
    name: 'Population distribution - demography',
    value: 'Population distribution - demography',
  },
  {
    name: 'Production and industrial facilities',
    value: 'Production and industrial facilities',
  },
  {name: 'Sea regions', value: 'Sea regions'},
  {name: 'Soil', value: 'Soil'},
  {name: 'Species distribution', value: 'Species distribution'},
  {name: 'Statistical units', value: 'Statistical units'},
  {
    name: 'Utility and governmental services',
    value: 'Utility and governmental services',
  },
  {
    name: 'Meteorological geographical features',
    value: 'Meteorological geographical features',
  },
  {
    name: 'Atmospheric Conditions and meteorological geographical features',
    value: 'Atmospheric Conditions and meteorological geographical features',
  },
];
export const SORTBYVALUES: any[] = [
  {name: 'None', value: 'None'},
  {name: 'Title', value: 'title'},
  {name: 'Date', value: 'date'},
  {name: 'Bbox', value: 'bbox'},
];
export const TYPES: any[] = [
  {name: 'None', value: 'None'},
  {name: 'Datasource', value: 'datasource'},
  {name: 'Service', value: 'service'},
  {name: 'Application', value: 'application'},
  {name: 'Feature catalogue', value: 'feature catalogue'},
];
